import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { PostList } from "~/features/Post";

const Home: NextPage = () => (
  <>
    <Head>
      <title>Chronicles</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/logo.png" />
    </Head>
    <PostList />
  </>
);

export default Home;
